version: '3.9'

services:
  bpmn-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ASSIGNEES: ${ASSIGNEES}
    ports:
      - "5050:5000"
    volumes:
      - ./bpmn:/app/bpmn
      - ./templates:/app/templates
      - ./assignee:/assignee            # Mount host ./assignee to container /assignee for syncing JSON
      - ./pending:/app/pending
      - ./process:/process
    env_file:
      - .env
